"""Shared application constants."""

MEDICATION_PRESETS: list[dict] = [
    {
        "id": "lisinopril",
        "name": "Lisinopril",
        "dosage": "10mg",
        "frequency": "Daily",
        "scheduled_times": ["08:00"],
        "instructions": "Take with or without food",
    },
    {
        "id": "metformin",
        "name": "Metformin",
        "dosage": "500mg",
        "frequency": "Twice daily",
        "scheduled_times": ["08:00", "20:00"],
        "instructions": "Take with meals",
    },
    {
        "id": "atorvastatin",
        "name": "Atorvastatin",
        "dosage": "20mg",
        "frequency": "Daily",
        "scheduled_times": ["20:00"],
        "instructions": "Take in the evening",
    },
    {
        "id": "amlodipine",
        "name": "Amlodipine",
        "dosage": "5mg",
        "frequency": "Daily",
        "scheduled_times": ["08:00"],
        "instructions": "Take at the same time each day",
    },
    {
        "id": "omeprazole",
        "name": "Omeprazole",
        "dosage": "20mg",
        "frequency": "Daily",
        "scheduled_times": ["08:00"],
        "instructions": "Take before breakfast",
    },
    {
        "id": "levothyroxine",
        "name": "Levothyroxine",
        "dosage": "50mcg",
        "frequency": "Daily",
        "scheduled_times": ["07:00"],
        "instructions": "Take on an empty stomach",
    },
    {
        "id": "aspirin",
        "name": "Aspirin",
        "dosage": "81mg",
        "frequency": "Daily",
        "scheduled_times": ["08:00"],
        "instructions": "Take with food if stomach upset occurs",
    },
    {
        "id": "vitamin-d3",
        "name": "Vitamin D3",
        "dosage": "1000 IU",
        "frequency": "Daily",
        "scheduled_times": ["08:00"],
        "instructions": "Take with a meal",
    },
    {
        "id": "donepezil",
        "name": "Donepezil",
        "dosage": "5mg",
        "frequency": "Daily",
        "scheduled_times": ["20:00"],
        "instructions": "Take at bedtime",
    },
    {
        "id": "furosemide",
        "name": "Furosemide",
        "dosage": "20mg",
        "frequency": "Daily",
        "scheduled_times": ["08:00"],
        "instructions": "Take in the morning",
    },
    {
        "id": "gabapentin",
        "name": "Gabapentin",
        "dosage": "300mg",
        "frequency": "Twice daily",
        "scheduled_times": ["08:00", "20:00"],
        "instructions": "Take as directed",
    },
    {
        "id": "acetaminophen",
        "name": "Acetaminophen",
        "dosage": "500mg",
        "frequency": "As needed",
        "scheduled_times": ["08:00", "14:00", "20:00"],
        "instructions": "Do not exceed recommended daily limit",
    },
]
