/** Medication presets — mirrors backend/app/constants.py for static UI use. */
window.MEDICATION_PRESETS = [
  {
    id: "lisinopril",
    name: "Lisinopril",
    dosage: "10mg",
    frequency: "Daily",
    scheduled_times: ["08:00"],
    instructions: "Take with or without food",
  },
  {
    id: "metformin",
    name: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    scheduled_times: ["08:00", "20:00"],
    dose_instructions: ["Take with breakfast", "Take with dinner"],
  },
  {
    id: "atorvastatin",
    name: "Atorvastatin",
    dosage: "20mg",
    frequency: "Daily",
    scheduled_times: ["20:00"],
    instructions: "Take in the evening",
  },
  {
    id: "amlodipine",
    name: "Amlodipine",
    dosage: "5mg",
    frequency: "Daily",
    scheduled_times: ["08:00"],
    instructions: "Take at the same time each day",
  },
  {
    id: "omeprazole",
    name: "Omeprazole",
    dosage: "20mg",
    frequency: "Daily",
    scheduled_times: ["08:00"],
    instructions: "Take before breakfast",
  },
  {
    id: "levothyroxine",
    name: "Levothyroxine",
    dosage: "50mcg",
    frequency: "Daily",
    scheduled_times: ["07:00"],
    instructions: "Take on an empty stomach",
  },
  {
    id: "aspirin",
    name: "Aspirin",
    dosage: "81mg",
    frequency: "Daily",
    scheduled_times: ["08:00"],
    instructions: "Take with food if stomach upset occurs",
  },
  {
    id: "vitamin-d3",
    name: "Vitamin D3",
    dosage: "1000 IU",
    frequency: "Daily",
    scheduled_times: ["08:00"],
    instructions: "Take with a meal",
  },
  {
    id: "donepezil",
    name: "Donepezil",
    dosage: "5mg",
    frequency: "Daily",
    scheduled_times: ["20:00"],
    instructions: "Take at bedtime",
  },
  {
    id: "furosemide",
    name: "Furosemide",
    dosage: "20mg",
    frequency: "Daily",
    scheduled_times: ["08:00"],
    instructions: "Take in the morning",
  },
  {
    id: "gabapentin",
    name: "Gabapentin",
    dosage: "300mg",
    frequency: "Twice daily",
    scheduled_times: ["08:00", "20:00"],
    dose_instructions: ["Take in the morning", "Take in the evening"],
  },
  {
    id: "acetaminophen",
    name: "Acetaminophen",
    dosage: "500mg",
    frequency: "As needed",
    scheduled_times: ["08:00", "14:00", "20:00"],
    dose_instructions: [
      "Take with breakfast if needed",
      "Take with lunch if needed",
      "Do not exceed recommended daily limit",
    ],
  },
];

/** Medical history presets — mirrors backend/app/constants.py for static UI use. */
window.MEDICAL_HISTORY_PRESETS = [
  {
    id: "type2-diabetes",
    category: "condition",
    title: "Type 2 diabetes",
    description: "Managed with diet, exercise, and medication",
  },
  {
    id: "hypertension",
    category: "condition",
    title: "Hypertension",
    description: "High blood pressure",
  },
  {
    id: "heart-disease",
    category: "condition",
    title: "Heart disease",
    description: "Coronary artery disease or heart failure",
  },
  {
    id: "copd",
    category: "condition",
    title: "COPD",
    description: "Chronic obstructive pulmonary disease",
  },
  {
    id: "asthma",
    category: "condition",
    title: "Asthma",
    description: "Uses rescue inhaler as needed",
  },
  {
    id: "arthritis",
    category: "condition",
    title: "Arthritis",
    description: "Joint pain and stiffness",
  },
  {
    id: "dementia",
    category: "condition",
    title: "Dementia",
    description: "Memory and cognitive support needed",
  },
  {
    id: "penicillin-allergy",
    category: "allergy",
    title: "Penicillin",
    description: "Allergic reaction to penicillin antibiotics",
  },
  {
    id: "sulfa-allergy",
    category: "allergy",
    title: "Sulfa drugs",
    description: "Allergic reaction to sulfonamide medications",
  },
  {
    id: "peanut-allergy",
    category: "allergy",
    title: "Peanuts",
    description: "Food allergy — avoid peanut products",
  },
  {
    id: "shellfish-allergy",
    category: "allergy",
    title: "Shellfish",
    description: "Food allergy — avoid shellfish",
  },
  {
    id: "latex-allergy",
    category: "allergy",
    title: "Latex",
    description: "Avoid latex gloves and products",
  },
  {
    id: "hip-replacement",
    category: "surgery",
    title: "Hip replacement",
    description: "Total hip arthroplasty",
  },
  {
    id: "knee-replacement",
    category: "surgery",
    title: "Knee replacement",
    description: "Total knee arthroplasty",
  },
  {
    id: "bypass-surgery",
    category: "surgery",
    title: "Coronary bypass",
    description: "CABG — coronary artery bypass graft",
  },
  {
    id: "cataract-surgery",
    category: "surgery",
    title: "Cataract surgery",
    description: "Lens replacement",
  },
  {
    id: "pacemaker",
    category: "note",
    title: "Pacemaker",
    description: "Implanted cardiac device",
  },
  {
    id: "fall-risk",
    category: "note",
    title: "Fall risk",
    description: "History of falls — mobility assistance recommended",
  },
  {
    id: "hearing-aid",
    category: "note",
    title: "Hearing aid",
    description: "Uses hearing aids",
  },
  {
    id: "wheelchair",
    category: "note",
    title: "Uses wheelchair",
    description: "Limited mobility — wheelchair for longer distances",
  },
];

/** Healthcare contact presets — mirrors backend/app/constants.py for static UI use. */
window.CONTACT_PRESETS = [
  {
    id: "primary-care-doctor",
    name: "Dr. Patel",
    contact_type: "doctor",
    specialty: "Primary care",
    phone: "555-0100",
    address: "123 Main Street Clinic",
    is_primary: true,
  },
  {
    id: "cardiologist",
    name: "Dr. Nguyen",
    contact_type: "doctor",
    specialty: "Cardiology",
    phone: "555-0101",
    address: "456 Heart Center Drive",
    is_primary: false,
  },
  {
    id: "geriatrician",
    name: "Dr. Williams",
    contact_type: "doctor",
    specialty: "Geriatrics",
    phone: "555-0102",
    address: "789 Senior Care Blvd",
    is_primary: false,
  },
  {
    id: "neurologist",
    name: "Dr. Chen",
    contact_type: "doctor",
    specialty: "Neurology",
    phone: "555-0103",
    address: "321 Brain & Spine Center",
    is_primary: false,
  },
  {
    id: "local-hospital",
    name: "Community General Hospital",
    contact_type: "hospital",
    specialty: "Emergency & inpatient",
    phone: "555-0200",
    address: "100 Hospital Way",
    is_primary: false,
  },
  {
    id: "medical-center",
    name: "University Medical Center",
    contact_type: "hospital",
    specialty: "Full-service hospital",
    phone: "555-0201",
    address: "200 University Ave",
    is_primary: false,
  },
  {
    id: "cvs-pharmacy",
    name: "CVS Pharmacy",
    contact_type: "pharmacy",
    specialty: "Retail pharmacy",
    phone: "555-0300",
    address: "500 Oak Street",
    is_primary: false,
  },
  {
    id: "walgreens-pharmacy",
    name: "Walgreens Pharmacy",
    contact_type: "pharmacy",
    specialty: "Retail pharmacy",
    phone: "555-0301",
    address: "600 Maple Avenue",
    is_primary: false,
  },
  {
    id: "emergency-911",
    name: "Emergency — 911",
    contact_type: "emergency",
    specialty: "Life-threatening emergencies",
    phone: "911",
    address: null,
    is_primary: false,
  },
  {
    id: "poison-control",
    name: "Poison Control",
    contact_type: "emergency",
    specialty: "Poisoning & overdose",
    phone: "800-222-1222",
    address: null,
    is_primary: false,
  },
];
